Merge task/lists in main
finderings/ru-study-python pull request #1
Opened 2023-06-22 08:05 UTC by finderings

Добавил .DS_Store в .gitignore, удалил скип тестов и написал решения в lists.py. Тесты проходят, линтеры ошибок не выдают

2023-06-23 08:17 UTC, aleksandr-semenov-dbp requested changes

2023-06-23 08:17 UTC, aleksandr-semenov-dbp commented on lists/lists.py
> +        while low <= high:
Здесь по заданию надо реализовать рекурсивно

2023-06-23 11:40 UTC, finderings commented on lists/lists.py
> +        while low <= high:
Исправил

2023-06-26 08:59 UTC, aleksandr-semenov-dbp approved these changes

2023-06-26 09:18 UTC, merged